# Generated by Django 3.0.7 on 2021-12-14 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0002_auto_20211213_1715'),
    ]

    operations = [
        migrations.AddField(
            model_name='facultad',
            name='email',
            field=models.EmailField(default='', editable=False, max_length=40),
        ),
    ]
