# Generated by Django 4.0 on 2022-01-05 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0003_facultad_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vacunas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proveedor', models.CharField(max_length=40)),
                ('fecha_creacion', models.DateField()),
                ('pais_origen', models.CharField(max_length=40)),
                ('dolor', models.BooleanField(choices=[(0, 'Poco'), (1, 'Normal'), (2, 'Mucho')], default=0)),
            ],
        ),
        migrations.DeleteModel(
            name='autos',
        ),
    ]
