# Generated by Django 4.0 on 2022-01-05 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0004_vacunas_delete_autos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vacunas',
            name='dolor',
        ),
        migrations.AddField(
            model_name='vacunas',
            name='grado_de_dolor',
            field=models.IntegerField(choices=[(0, 'Poco'), (1, 'Normal'), (2, 'Mucho')], default=0),
        ),
    ]
