# Generated by Django 4.0 on 2022-01-07 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0005_remove_vacunas_dolor_vacunas_grado_de_dolor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Barbijos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=40)),
                ('tamanio', models.CharField(max_length=20)),
                ('precio', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='inmuebles',
        ),
        migrations.AlterField(
            model_name='facultad',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='vacunas',
            name='grado_de_dolor',
            field=models.IntegerField(choices=[(1, 'Poco'), (2, 'Normal'), (3, 'Mucho')], default=0),
        ),
        migrations.AlterField(
            model_name='vacunas',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
