# Generated by Django 4.0 on 2022-01-07 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0006_barbijos_delete_inmuebles_alter_facultad_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Oximetros',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=40)),
                ('modelo', models.CharField(max_length=20)),
                ('precio', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='facultad',
        ),
    ]
